### ISSUE TITLE
Not working on NuxtJS

### ISSUE THREAD

**Issue by jasonburn** [overtrue/vue-avatar-cropper#614]
Hi,

I've been using this library on our old app using Laravel and plain Vue 2.
We are now rebuilding our app and decided to use NuxtJS as our SPA front-end.

It is working perfectly fine on our old app but somehow I got an error when using it on Nuxt.

Nuxt: `v2.15.8`
Vue: `v2.6.14`

I'm now sure if this is related to Jquery as that is the only thing I can think of not present in NuxtJS.
Is this the case?

TIA

**Comment by ferretwithaberet** [comment]
Can you also provide the error traceback?

**Comment by jasonburn** [comment]
Here is the error log:

```
avatar-cropper.esm.js?eb0f:1 
        
       Uncaught TypeError: Object(...) is not a function
    at eval (avatar-cropper.esm.js?eb0f:1:1)
    at Module../node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js (app.js:10459:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (index.js?!./node_modules/vue-loader/lib/index.js?!./components/Member/Profile/Form.vue?vue&type=script&lang=js&:6:76)
    at Module../node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./components/Member/Profile/Form.vue?vue&type=script&lang=js& (app.js:20067:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (Form.vue?5e34:1:1)
    at Module../components/Member/Profile/Form.vue?vue&type=script&lang=js& (app.js:7659:1)
eval @ avatar-cropper.esm.js?eb0f:1
./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js @ app.js:10459
__webpack_require__ @ runtime.js:854
fn @ runtime.js:151
eval @ index.js?!./node_modules/vue-loader/lib/index.js?!./components/Member/Profile/Form.vue?vue&type=script&lang=js&:6
./node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./components/Member/Profile/Form.vue?vue&type=script&lang=js& @ app.js:20067
__webpack_require__ @ runtime.js:854
fn @ runtime.js:151
eval @ Form.vue?5e34:1
./components/Member/Profile/Form.vue?vue&type=script&lang=js& @ app.js:7659
__webpack_require__ @ runtime.js:854
fn @ runtime.js:151
eval @ Form.vue?041c:1
./components/Member/Profile/Form.vue @ app.js:7647
__webpack_require__ @ runtime.js:854
fn @ runtime.js:151
eval @ index.js:514
./.nuxt/components/index.js @ app.js:71
__webpack_require__ @ runtime.js:854
fn @ runtime.js:151
eval @ plugin.js?2573:1
./.nuxt/components/plugin.js @ app.js:251
__webpack_require__ @ runtime.js:854
fn @ runtime.js:151
eval @ index.js:53
./.nuxt/index.js @ app.js:275
__webpack_require__ @ runtime.js:854
fn @ runtime.js:151
eval @ client.js:57
eval @ client.js:1297
./.nuxt/client.js @ app.js:59
__webpack_require__ @ runtime.js:854
fn @ runtime.js:151
0 @ app.js:32988
__webpack_require__ @ runtime.js:854
checkDeferredModules @ runtime.js:46
webpackJsonpCallback @ runtime.js:33
(anonymous) @ app.js:1
Show 8 more frames
vue.runtime.esm.js?2b0e:8484 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
client.js?1b93:95 [HMR] connected
client.js?1b93:195 [HMR] bundle 'client' has 25 warnings
client.js?1b93:196 ./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:6752-6753"export 'createCommentVNode' (imported as 's') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:7577-7578"export 'createCommentVNode' (imported as 's') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:7593-7594"export 'createCommentVNode' (imported as 's') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:6621-6622"export 'createElementBlock' (imported as 'p') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:6647-6648"export 'createElementBlock' (imported as 'p') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:6766-6767"export 'createElementBlock' (imported as 'p') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:7607-7608"export 'createElementBlock' (imported as 'p') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:6777-6778"export 'createElementVNode' (imported as 'c') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:6948-6949"export 'createElementVNode' (imported as 'c') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:6959-6960"export 'createElementVNode' (imported as 'c') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:6970-6971"export 'createElementVNode' (imported as 'c') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:7229-7230"export 'createElementVNode' (imported as 'c') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:7240-7241"export 'createElementVNode' (imported as 'c') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:7404-7405"export 'createElementVNode' (imported as 'c') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:425-426"export 'defineComponent' (imported as 'i') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:6668-6669"export 'normalizeClass' (imported as 'l') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:6617-6618"export 'openBlock' (imported as 'o') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:6643-6644"export 'openBlock' (imported as 'o') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:6762-6763"export 'openBlock' (imported as 'o') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:7603-7604"export 'openBlock' (imported as 'o') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:7382-7383"export 'toDisplayString' (imported as 'm') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:7546-7547"export 'toDisplayString' (imported as 'm') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:7029-7030"export 'withModifiers' (imported as 'u') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:7272-7273"export 'withModifiers' (imported as 'u') was not found in 'vue'./node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js 1:7436-7437"export 'withModifiers' (imported as 'u') was not found in 'vue'

```

**Comment by nor1c** [comment]
any solution?
