### ISSUE TITLE
Could not resolve "@babel/runtime/helpers...

### ISSUE THREAD

**Issue by mityaua** [overtrue/vue-avatar-cropper#877]
My app doesn't start without **@babel/runtime** library when I use vue-avatar-cropper. But in other projects the application runs without this library. How can I get rid of this dependency?

```bash
Could not resolve "@babel/runtime/helpers/slicedToArray"

    node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js:1:13:
      1 │ import e from"@babel/runtime/helpers/slicedToArray";import t from"@babel/runtime/helpers/asyncToGenerator";import r from"@babel/runt...
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime/helpers/slicedToArray" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@babel/runtime/helpers/asyncToGenerator"

    node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js:1:65:
      1 │ ...runtime/helpers/slicedToArray";import t from"@babel/runtime/helpers/asyncToGenerator";import r from"@babel/runtime/regenerator";i...
        ╵                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime/helpers/asyncToGenerator" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@babel/runtime/regenerator"

    node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js:1:120:
      1 │ ...bel/runtime/helpers/asyncToGenerator";import r from"@babel/runtime/regenerator";import"cropperjs/dist/cropper.css";import a from"...
        ╵                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime/regenerator" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle.

app\node_modules\esbuild\lib\main.js:1472
  let error = new Error(text);
              ^

Error: Build failed with 3 errors:
node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js:1:13: ERROR: Could not resolve "@babel/runtime/helpers/slicedToArray"
node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js:1:65: ERROR: Could not resolve "@babel/runtime/helpers/asyncToGenerator"
node_modules/vue-avatar-cropper/dist/avatar-cropper.esm.js:1:120: ERROR: Could not resolve "@babel/runtime/regenerator"
    at failureErrorWithLog (app\node_modules\esbuild\lib\main.js:1472:15)    
    at app\node_modules\esbuild\lib\main.js:945:25
    at app\node_modules\esbuild\lib\main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v20.16.0
```

"vue": "^3.4.38",
"vue-avatar-cropper": "^6.1.1",
"typescript": "~5.4.5",
"vite": "^5.4.10",

**Comment by mityaua** [comment]
@overtrue any thoughts?

``` json {
	"dependencies": {
		"@babel/runtime": "^7.27.6",
		"axios": "^1.9.0",
		"pinia": "^3.0.3",
		"vue": "^3.5.16",
		"vue-avatar-cropper": "^6.1.1",
		"vue-i18n": "^11.1.5",
		"vue-router": "^4.5.1"
	},
	"devDependencies": {
		"@quasar/vite-plugin": "^1.9.0",
		"@tsconfig/node20": "^20.1.5",
		"@types/jsdom": "^21.1.7",
		"@types/node": "^22.15.30",
		"@vitejs/plugin-vue": "^5.2.4",
		"@vue/tsconfig": "^0.7.0",
		"sass": "1.89.1",
		"typescript": "~5.7.3",
		"vite": "^6.3.5",
		"vue-tsc": "^2.2.10"
	}
```
